services:
  bot:
    build: .
    image: benbot
    container_name: benbot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - ./.env
    command: python -u main.py
